# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logspace_addcpp <- function(logx, logy) {
    .Call('_HMMclone_logspace_addcpp', PACKAGE = 'HMMclone', logx, logy)
}

viterbi <- function(emission, transition, observations) {
    .Call('_HMMclone_viterbi', PACKAGE = 'HMMclone', emission, transition, observations)
}

